import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localfont from "next/font/local";
const inter = Inter({ subsets: ["latin"] });

const bd = localfont({
  src: [
    {
      path: "../../public/font/BeautiqueDisplay-Medium-BF63fd5fa832247.otf",
      // weight: "100",
    },
  ],
   variable:"--beautique-display"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bd.variable} ${inter.className}`}>{children}</body>
    </html>
  );
}
